version: '2'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:alpine
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: zhanshu-server
    links:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
    environment:
      # DATABASE_URL: postgres://postgres@db:5432/zhanshu-server?pool=25&encoding=unicode&schema_search_path=public
      DEVISE_JWT_SECRET_KEY: RANDOM_SECRET
      REDIS_URL: redis://redis:6379
      QINIU_ENABLED: 'yes'
      QINIU_ACCESS_KEY: empty
      QINIU_SECRET_KEY: empty
      QINIU_BUCKET: empty
      QINIU_HOST: empty
      WECHAT_APP_ID: empty
      WECHAT_APP_SECRET: empty
      WECHAT_APP_TOKEN: empty
      WECHAT_APP_ENCODING_AES_KEY: empty
